import { Grid } from '@mui/material';
import { Box } from '@mui/system';
import { useSession, getSession } from 'next-auth/react';
import Head from 'next/head';
import ChatSidebar from '../components/Chat/ChatSidebar';
import OpenConversation from '../components/Chat/OpenConversation';
import { useConversations } from '../context/ConversationsProvider';
import Header from '../components/Header.js'

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: { session }
  }
}

export default function Chat() {
  const { data: session, status } = useSession();
  console.log('profile.js session: ', session)

  const { selectedConversation } = useConversations();

  return (
    <>
        <Head>
          <title>Chat</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/social-media.png" />
        </Head>

      <div style={{ paddingTop: '0px' }}>
        <Box sx={{ flexGrow: 1 }}>
          <Grid container spacing={2}>
            <Grid item xs={4}>
              <div className="d-flex" style={{ height: '100vh', width: '300px' }}>
                <ChatSidebar username={session.user.email} />
              </div>
            </Grid>
            <Grid item xs={8}>
              {selectedConversation && <OpenConversation username={session.user.email}/>}
            </Grid>
          </Grid>
        </Box>
      </div>
    </>
  )
}
