import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/react';
import Header from '../components/Header.js'
import Sidebar from '../components/Sidebar'
import SidebarRight from '../components/SidebarRight'
import MediaItem from '../components/MediaItem'
import Footer from '../components/Footer'
import { Grid, Pagination } from '@mui/material'


export default function Home() {

  const {data: session, status } = useSession();
  console.log(session)

  const user = session?.user;

  return (
    <>

      <Head>
        <title>Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Grid container spacing={3}>
        <Grid item xs={2}>

          <Sidebar />
        </Grid>
        <Grid item xs={8}>
          <MediaItem />
          <Pagination count={10} />
        </Grid>
        <Grid item xs={2}>
          <SidebarRight />
        </Grid>
      </Grid>
      <div className={styles.footer}>
        <Footer />

      {user && (
        <>
          <img src={session.user.image} height= '50' width ='50'/>
          <h2>Welcome, {user.name}</h2>
          <button onClick={() => signOut()}>Sign Out</button>
        </>
      )}
      
      {!user &&(
        <>
        <button onClick={() => signIn()}>Sign In</button>
        </>
      )}
    

      </div>
    </>

      
  )
}
