import Head from 'next/head';
import styles from '../styles/Home.module.css'

// needed for auth
import React from 'react';
import { getSession, signIn, signOut, useSession } from 'next-auth/react';

// needed for structure and css
import Sidebar from '../components/Sidebar'
import SidebarRight from '../components/SidebarRight'
import MediaItem from '../components/MediaItem'
import { Grid, Pagination, Box } from '@mui/material'
import { useEffect, useState } from 'react';

const Chance = require('chance');
const chance = new Chance();

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: { session }
  }
}

export default function Home() {
  const [data, setData] = useState([]);
  const [page, setPage] = useState(1);

  const pageSize = 6;
  const numPages = Math.ceil(data.length / pageSize);
  const startingData = (page - 1) * pageSize;
  const endingData = startingData + pageSize;

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/social-media.png" />
      </Head>

      <main>
      <Grid className={styles['main-grid']} container spacing={2} sx={{}}>
      <Grid item xs={12}>
          <Box sx={{padding: '3vh'}}></Box>
        </Grid>
        <Grid item xs={2}>
          <Sidebar setData={setData}/>
        </Grid>
        <Grid item xs={8}>
          <Grid container spacing={3} sx={{margin: 'auto', paddingBottom: "last-child"}}>
            {data.slice(startingData, endingData).map(item => (
              <Grid key={chance.guid()} item xs={4}>
                <MediaItem item={item}/>
              </Grid>
            ))}
          </Grid>
          {data.length > 0 ? <Pagination onChange={(_, page) => setPage(page)} count={numPages} /> : null}
        </Grid>
        <Grid item xs={2}>
          <SidebarRight />
        </Grid>
      </Grid>
      </main>
    </>

  )
}
