import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'


export default function Profile() {
  return (
    <div>
      <Header />
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Profile Page</h1>
        <Sidebar />
      </main>
    </div>
  )
}
